// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAch6CsKGZQfMMiJFqUqp9JIgfxqwCDXR8',
    appId: '1:841872909265:web:2ab2b8cc47b522a01376f0',
    messagingSenderId: '841872909265',
    projectId: 'word-constructure',
    authDomain: 'word-constructure.firebaseapp.com',
    storageBucket: 'word-constructure.appspot.com',
    measurementId: 'G-CPX9WT0FZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5adNZvs2R2qzrtU1QaG85Itpb5Q54SPY',
    appId: '1:841872909265:android:8213b934f878acab1376f0',
    messagingSenderId: '841872909265',
    projectId: 'word-constructure',
    storageBucket: 'word-constructure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnIjwO0Uh1ieGL77YsRZQfRPt1MRW6Pt0',
    appId: '1:841872909265:ios:ff39ffee2b612f811376f0',
    messagingSenderId: '841872909265',
    projectId: 'word-constructure',
    storageBucket: 'word-constructure.appspot.com',
    iosClientId: '841872909265-kt3j33ci3d6lb574vbcv21ucd45866hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordStructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnIjwO0Uh1ieGL77YsRZQfRPt1MRW6Pt0',
    appId: '1:841872909265:ios:ff39ffee2b612f811376f0',
    messagingSenderId: '841872909265',
    projectId: 'word-constructure',
    storageBucket: 'word-constructure.appspot.com',
    iosClientId: '841872909265-kt3j33ci3d6lb574vbcv21ucd45866hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordStructure',
  );
}
